name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.1
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Synthetizer/Synthetizer/
    - name: Build
      run: dotnet build --no-restore
      working-directory: Synthetizer/Synthetizer/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Synthetizer/Synthetizer/
